sonar.projectKey=AndresD902_BACKEND
sonar.organization=andresd902
sonar.projectName=EmployeesAdministration Backend

sonar.sourceEncoding=UTF-8

sonar.sources=auth-service/src,contract-service/src,employee-service/src,history-service/src,report-service/src,super-admin-service/src,vacation-service/src
sonar.tests=auth-service/tests,contract-service/tests,employee-service/tests,history-service/tests,report-service/tests,super-admin-service/tests,vacation-service/tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

sonar.typescript.tsconfigPaths=auth-service/tsconfig.json,contract-service/tsconfig.json,employee-service/tsconfig.json,history-service/tsconfig.json,report-service/tsconfig.json,super-admin-service/tsconfig.json,vacation-service/tsconfig.json
sonar.javascript.lcov.reportPaths=auth-service/coverage/lcov.info,contract-service/coverage/lcov.info,employee-service/coverage/lcov.info,history-service/coverage/lcov.info,report-service/coverage/lcov.info,super-admin-service/coverage/lcov.info,vacation-service/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.runtime/**,**/logs/**,**/*.config.js,**/*.config.ts,**/migrations/**,docker/**,requests.http
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/tests/**,**/migrations/**,**/src/server.ts,**/src/app.ts,**/src/config/**,**/src/routes/**
