sonar.projectKey=AndresD902_BACKEND
sonar.organization=andresd902
sonar.sources=auth-service/src
sonar.tests=auth-service/tests
sonar.test.inclusions=auth-service/tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=auth-service/coverage/lcov.info